### ISSUE TITLE
Update Readme Gif preview📢

### ISSUE THREAD

**Issue by fineanmol** [fineanmol/Annoying-submit-button#15]
### The gif preview needs to be update in the readme file, as the project has been updated since beginning.

**Comment by ruchi-115** [comment]
Hey, I'm interested to fix this issue. Can you please assign it to me?

**Comment by vikkastiwari** [comment]
Actually, I have created a PR for the same check if fine, else @ruchi-115 can continue with that.

**Comment by fineanmol** [comment]
@vikkastiwari , let @ruchi-115 contribute as well.
