### ISSUE TITLE
Change emoji when Submit button turns green

### ISSUE THREAD

**Issue by KhushiTayal** [fineanmol/Annoying-submit-button#48]
Use angry emoji when the button is red (cannot submit)
Use smiling emoji when the button is green (can submit)
Please approve and assign this issue to me.

**Comment by KhushiTayal** [comment]
@fineanmol

**Comment by skyrunner360** [comment]
@KhushiTayal Let me know if you need any help with this. (It's a great idea btw!)

**Comment by KhushiTayal** [comment]
@fineanmol I have generated PR for this emoji transition feature. Please check.
