### ISSUE TITLE
Contributors headcount is not increasing in readme 💭

### ISSUE THREAD

**Issue by fineanmol** [fineanmol/Annoying-submit-button#8]
### Contributors Count is not increasing in readme file 💭. It is showing only 4 names

**Comment by vaibhavmishra4g** [comment]
Assign me the task I'll resolve it

**Comment by vaibhavmishra4g** [comment]
yep it has some refresh bug or it'll take 24 hrs I checked it on the website

**Comment by vikkastiwari** [comment]
@fineanmol, The issue is fixed now the contributor's count is updated correctly.
