### ISSUE TITLE
Social media links hover color is ill-suited.

### ISSUE THREAD

**Issue by shiningshani** [fineanmol/Annoying-submit-button#92]
I noticed that the color of your sites social media link on hovering are misplaced. 
Being a new entrant into open source field, I wanted to make them proper.

Can you assign me this task??

**Comment by artizticamit** [comment]
Hello, I also noticed that the social media links hover have ill suited colors and would like to work on it.
Can you assign it to me?

**Comment by shiningshani** [comment]
@fineanmol I'm working on it and i will complete it by today. Please dont assign it to  @artizticamit or any other person.

**Comment by shiningshani** [comment]
Actually someone else has fixed this issue.
closing it then.
